### ISSUE TITLE
[Home.md] Broken Links

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-coffeehouse#111]
- 다음 link가 깨져 있네요

<br>
<img width=280 src="https://github.com/cloud-barista/cb-coffeehouse/assets/46367962/a9d3bb9c-45c4-4936-87f0-49e1b7a66f34">
<br>

**Comment by yunkon-kim** [comment]
@powerkimhub 감사합니다.

wiki와 docs간에 sync 기능이 동작중인데, docs 디렉토리만 카테고리 별로 정리하는 바람에 이슈가 발생했었습니다.

우선 [Git-Tips-&-Tricks.md](https://github.com/cloud-barista/cb-coffeehouse/blob/main/docs/Git-and-Github/Git-Tips-%26-Tricks.md)을 참고하시기 바랍니다.

"rebase로 커밋 합치기"는 외부 소스인데요. 확인해보니 해당 페이지가 없어진 상황입니다. 다른 소스를 찾아서 변경해 놓겠습니다.
