### ISSUE TITLE
Contribution Academy

### ISSUE THREAD

**Issue by hermitkim1** [cloud-barista/cb-coffeehouse#26]
안녕하세요!

2021 컨트리뷰션 아카데미를 통해 여러분과 함께 공개SW를 개발하게 되어 진심으로 기쁩니다 😍 

<ins>**클라우드바리스타에 대해 여러분의 이야기(궁금한점, 건의사항, 바라는점 등)을 코멘트로 남겨주세요**</ins> 🙏

**Comment by junhyunk** [comment]
:tada:

**Comment by seokho-son** [comment]
CB-Tumblebug 리더 손석호 입니다~ CB-TB 홍보하러 왔습니다 ㅎㅎ
- CB-TB 저장소: https://github.com/cloud-barista/cb-tumblebug 
- CB-TB 슬랙 채널: https://cloud-barista.slack.com/archives/CJQ7575PU

**Comment by hermitkim1** [comment]
빠르시네요 ㅎㅎ

**Comment by dongjae** [comment]
멘티님들의 다양한 의견과 활동을 기대해 봅니다.^^. 키미(KIMY)-커피하우스가 갈 수록 번창하는군요.

**Comment by powerkimhub** [comment]
클라우드바리스타 입소를 환영합니다~ 

[CB-Spider](https://github.com/cloud-barista/cb-spider) 리더입니다만...

- https://github.com/cloud-barista/cb-spider/wiki
- 궁금하면, 500원^^

**Comment by benz-e-class** [comment]
잘부탁드리겠습니다 ^^

**Comment by guswns1659** [comment]
안녕하세요 ~ 프레임워크 주 언어를 go로 선택하신 이유가 궁금합니다 ~

**Comment by ChobobDev** [comment]
잘부탁드립니다~

**Comment by leedohun** [comment]
클라우드를 활용하는 프레임워크에서 terraform이 뜨고 있는 기술인데 CLI를선택하신 이유가 궁금합니다.

**Comment by jangh-lee** [comment]
- 건의 : 올해도 코로나 상황이긴 하지만, 기술 세션을 많이 열어주셨으면좋겠어요. 오프라인이 어려우면 온라인으로라도!
- 건의 : 질문할 수 있는 별도의 공간을 안내해주세요, 질문만 올릴 수 있는 곳이요 ㅎㅎ
- 질문 : NCP네이버 클라우드도 지원예정인지 궁금하네요,
잘부탁드립니다.

**Comment by sypark9646** [comment]
잘부탁드립니다!!ㅎㅎ

**Comment by gbnam** [comment]
지난 멘티분들에 아쉬웠던 점은 어떤게 있으셨는지 궁금합니다 ㅎ

**Comment by seokho-son** [comment]
> * 건의 : 올해도 코로나 상황이긴 하지만, 기술 세션을 많이 열어주셨으면좋겠어요. 오프라인이 어려우면 온라인으로라도!
> * 건의 : 질문할 수 있는 별도의 공간을 안내해주세요, 질문만 올릴 수 있는 곳이요 ㅎㅎ
> * 질문 : NCP네이버 클라우드도 지원예정인지 궁금하네요,
>   잘부탁드립니다.

Cloud-Barista Slack #new-contributor 채널을 활용하시면 되겠습니다!
https://cloud-barista.slack.com/archives/C02AA44LBPU

**Comment by seokho-son** [comment]
Cloud-Barista Slack 초대 링크 입니다! ^^
https://join.slack.com/t/cloud-barista/shared_invite/zt-bda8zhkg-tlOCr7_TdQGE_oUSz4mlkA
