### ISSUE TITLE
Creating and accessing an instance on MS Azure Platform

### ISSUE THREAD

**Issue by leedohun** [cloud-barista/cb-coffeehouse#29]
# Ms Azure

**Comment by leedohun** [comment]
![1](https://user-images.githubusercontent.com/33706689/129452169-9c24847e-bb7b-4fe3-bdad-46279a7bad7e.png)
![2](https://user-images.githubusercontent.com/33706689/129452170-16ed89b3-aafd-4034-bcea-f4d256db5b91.png)
![3](https://user-images.githubusercontent.com/33706689/129452171-1ca600ab-9e1c-4b68-8772-7c9114e379ce.png)
![4](https://user-images.githubusercontent.com/33706689/129452173-25306965-f4e0-41a7-af42-531f3d3d8dd9.png)
![5](https://user-images.githubusercontent.com/33706689/129452174-2ef5bfde-2fdc-4489-8f5a-c3ff8a43174c.png)
![6](https://user-images.githubusercontent.com/33706689/129452176-cf33aadc-a4b8-4f1d-bfb2-a85357a42a85.png)
![7](https://user-images.githubusercontent.com/33706689/129452177-ad47296f-9fa9-4312-a9e4-b412b5748b3c.png)
![8](https://user-images.githubusercontent.com/33706689/129452178-1e99b870-79e0-4b3b-afd9-28fd6e0c3be1.png)
![9](https://user-images.githubusercontent.com/33706689/129452179-1b14a9d7-e54b-42dc-ba76-87c22ab9333d.png)

**Comment by leedohun** [comment]
![10](https://user-images.githubusercontent.com/33706689/129454996-2923a69b-3a6c-4f5b-bd83-49b2b7dd238d.png)

**Comment by hermitkim1** [comment]
한 단계식 따라하면 Azure VM 생성 할 수 있도록 잘 작성해 주셨네요 👍 

그런데 컨텐츠는 docs에 markdown 파일을 생성하시고 그쪽으로 옮겨야할 것 같습니다 😅 

[가이드]
1. Forked repository의 docs 디렉토리 밑에 `Creating-and-accessing-an-instance-on-MS-Azure-Platform.md` 파일을 생성하시고요.
2. 해당 Markdown 문서에 위 컨텐츠를 옮겨주세요.
3. 추가로, 가독성을 위해 Section을 구분해 주시고요 ^^ (예시 참고해주세요.)
4. 그 다음 PR 해주시면 됩니다.

하시다가 궁금한 사항은 이슈에 코멘트 남겨주세요~~

[예시]
```
## 1. VM 생성하기 클릭
<p align="center">
  <img src="https://user-images.githubusercontent.com/33706689/129452169-9c24847e-bb7b-4fe3-bdad-46279a7bad7e.png" width="90%" height="90%" >
</p>

## 2. 리소스 그룹 생성
<p align="center">
  <img src="https://user-images.githubusercontent.com/33706689/129452170-16ed89b3-aafd-4034-bcea-f4d256db5b91.png" width="90%" height="90%" >
</p>

```

[결과]

## 1. VM 생성하기 클릭
<p align="center">
  <img src="https://user-images.githubusercontent.com/33706689/129452169-9c24847e-bb7b-4fe3-bdad-46279a7bad7e.png" width="90%" height="90%" >
</p>

## 2. 리소스 그룹 생성
<p align="center">
  <img src="https://user-images.githubusercontent.com/33706689/129452170-16ed89b3-aafd-4034-bcea-f4d256db5b91.png" width="90%" height="90%" >
</p>

**Comment by leedohun** [comment]
아!! 여긴 따로 사진만 저장하는 공간으로 작성하고 있었습니다. md 파일은 따로 제가 FORK한 레포지토리에 작성하고 있었고 오늘 중으로 PR을 할것입니다

**Comment by leedohun** [comment]
![11](https://user-images.githubusercontent.com/33706689/129464565-5e01d710-4e0a-4dcc-a0c3-73e2d8b0894d.png)
![12](https://user-images.githubusercontent.com/33706689/129464557-ce378630-ec3c-47d0-9a39-292bcc4575cd.png)
![13](https://user-images.githubusercontent.com/33706689/129464558-cb0b7712-cf53-40cb-82dd-d24c2ade38bd.png)
![14](https://user-images.githubusercontent.com/33706689/129464559-f277ca23-9e8d-4888-b8e4-8adf6365136d.png)
![15](https://user-images.githubusercontent.com/33706689/129464561-c51b54d3-bc0b-443c-9242-91d7ed216b7c.png)
![16](https://user-images.githubusercontent.com/33706689/129464562-1f81d80a-dcfe-4bd2-8c70-412b1f201d7f.png)
![17](https://user-images.githubusercontent.com/33706689/129464563-399440fa-dbf2-49d9-9b5f-4d11c04752a5.png)
![18](https://user-images.githubusercontent.com/33706689/129464564-1115a1b2-fa44-43ea-bcc8-6c9d34a70e52.png)

**Comment by hermitkim1** [comment]
Resolved
