### ISSUE TITLE
[1st Action Items] Creating and accessing an instance on GCP

### ISSUE THREAD

**Issue by eeeclipse** [cloud-barista/cb-coffeehouse#38]

**Comment by eeeclipse** [comment]
created wiki doc at 
https://github.com/cloud-barista/cb-coffeehouse/wiki/Creating-and-accessing-an-instance-on-GCP

**Comment by hermitkim1** [comment]
Thank you for your contribution 👍

**Comment by hermitkim1** [comment]
Your contribution on Wiki has been automatically synchronized to docs as follows: 
- [Home.md](https://github.com/cloud-barista/cb-coffeehouse/blob/main/docs/Home.md)
- [Creating-and-accessing-an-instance-on-GCP.md](https://github.com/cloud-barista/cb-coffeehouse/blob/main/docs/Creating-and-accessing-an-instance-on-GCP.md)

It's done by GitHub Actions 😄

**Comment by hermitkim1** [comment]
I think this issue has been resolved. 💯
