### ISSUE TITLE
Improve the GCP guide to creating and accessing an instance

### ISSUE THREAD

**Issue by hermitkim1** [cloud-barista/cb-coffeehouse#42]
Link: [[2021CA] GCP 에서 가상머신 생성 및 접속 내용](https://github.com/cloud-barista/cb-coffeehouse/blob/main/docs/Creating-and-accessing-an-instance-on-GCP.md)

**Comment by PARKINHYO** [comment]
주의할 점을 추가하고 싶습니다.

**Comment by limsg1234** [comment]
안녕하세요. 이미 가이드 완성이 너무 잘 되어 있지만, 조금 더 간결하게 수정을 할 수 있을 것 같습니다.
이슈 참여하겠습니다.

**Comment by kyungkoh** [comment]
안녕하세요, GCP에서 VM 접속 관련 부분 가이드를 추가 하고 싶습니다 
이슈 참여 하겠습니다.

**Comment by leedohun** [comment]
(제가 fork를 한 레포지토리와 CB-coffeehouse 레포지토리의 main 이력이 서로 달라져서 오류가 발생해 제가 fork를 한 레포지토리를 삭제한 뒤 다시 처리를 했습니다.) GCP 가이드 문서의 틀과 다른 cloud 문서의 틀을 동일하게 작업할 것이고, GCP CLI를 통해 VM 생성 및 GCP 리소스를 찾는 과정을 작성하고 싶습니다.   #39
