### ISSUE TITLE
nit: Typo exists in README

### ISSUE THREAD

**Issue by hermitkim1** [cloud-barista/cb-coffeehouse#60]
In [cb-coffeehouse README.md](https://github.com/cloud-barista/cb-coffeehouse/blob/main/README.md)

> Collaborators and contributros

[Proposed solution]
contributros -> contributors

**Comment by Muhammadwasi** [comment]
Hi @hermitkim1 , 

I would like to fix this typo.

**Comment by hermitkim1** [comment]
@Muhammadwasi

Welcome to Coffeehouse 🎉 

I am happy to receive your message that I didn't expect 😄 

You can proceed with this issue.
