### ISSUE TITLE
Need to enable Compute Engine API in GCP

### ISSUE THREAD

**Issue by yunkon-kim** [cloud-barista/cb-coffeehouse#71]
In GCP, It's necessary to enable Compute Engine API when I initially create a project and a credential.

I think it's helpful to add how to enable Compute Engine API in GCP to [A step-by-step guide to creating credentials of each cloud service provider](https://github.com/cloud-barista/cb-coffeehouse/blob/main/docs/A-step-by-step-guide-to-creating-credentials-of-each-cloud-service-provider.md)

**Comment by hermitkim1** [comment]
### Hint

![image](https://user-images.githubusercontent.com/7975459/134762519-31d1cbd5-9f14-4b88-adbd-d65967041956.png)
