### ISSUE TITLE
How about classifying cb-coffehouse's docs?

### ISSUE THREAD

**Issue by atg0831** [cloud-barista/cb-coffeehouse#74]
- cb-coffehouse의 docs의 문서 양이 많다 보니 신규 컨트리뷰터 입장에서는 어떤 것을 먼저 봐야할 지 그리고 각 문서가 어떤 내용을 담고 있는지 한눈에 파악하기 힘들 거 같다는 생각이 듭니다.
- CSP VM 생성 같은 경우, 각 CSP 별로 존재하는데 디렉토리를 하나 생성해서 그 안에 같이 분류하면 어떨까요? 
  - ex) AWS, GCP, Azure, Alibaba 등의 VM 생성 가이드 문서를 `VM 생성 가이드` 라는 디렉토리 안으로 넣는 형식
- CSP VM 생성 가이드 이외에도 비슷하거나 관련된 내용들을 묶어서 하나의 디렉토리 안에 넣으면 컨트리뷰터 입장에서는 쉽게 문서들을 파악할 수 있지 않을까 생각됩니다.

**Comment by hermitkim1** [comment]
@atg0831 안녕하세요!!

좋은 의견 감사드립니다 ^^

제안해주신 내용을 진행해 보시겠어요?

**Comment by atg0831** [comment]
네 제가 시간 되는대로 틈틈이 진행해볼게요!

**Comment by hermitkim1** [comment]
@atg0831, 넵 😄
